# ifndef __OBVIOUS_WRITING_REALIZ_RB_H
# define __OBVIOUS_WRITING_REALIZ_RB_H

#include "Writing_Capability_For_Stack_Template_en.h"

extern Writing_Capability_for_Stack_Template* new_Obvious_Writing_Realiz_for_Writing_Capability_for_Stack_Template(void (*Write)(r_type_ptr));
extern void free_Obvious_Writing_Realiz_for_Writing_Capability_for_Stack_Template(Writing_Capability_for_Stack_Template* tofree);
# endif
